Homework 2 code
rogtejada/sw-design-course pull request #2
Opened 2020-12-07 01:04 UTC by rogtejada

Add bank app with unit tests, based on previous design

2020-12-08 22:50 UTC, rafaritter44 requested changes
Gostei de ver na quantidade de testes! :smile: 

![image](https://user-images.githubusercontent.com/31143678/101550307-d31d0b00-398d-11eb-9d18-1cdbe7fdb3b3.png)

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/dto/TransferRequest.java
> +@Component
Isso deveria ser um Component?

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/mapper/AccountMapper.java
> +	public Account toEntity(AccountRequest request) {
Eu não sei se eu usaria um método mapper para isso, pois são objetos bem diferentes, o de entrada é bem simples e o de saída é bem mais complexo. Parece pra mim que seria um bom uso para uma factory.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/mapper/AccountMapper.java
> +	public AccountResponse toResponse(Account entity) {
Validar entrada null e fazer testes unitários para esse caso. Isso vale para todos os métodos mappers.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/mapper/AccountMapper.java
> +		ownerResponse.setCpf(entity.getOwner().getCpf());
Validar NPE e testar.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/controller/CreditAccountController.java
> +public class CreditAccountController {
Poderia validar os payloads com bean validation.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +	public Account getAccount(final UUID accountId) {
Poderia trabalhar com Optional em vez de exceptions nesse caso.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +	public BigDecimal getBalance(final UUID accountId) {
Poderia trabalhar com Optional em vez de exceptions nesse caso.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +		account.addStatement(new Statement(LocalDateTime.now(), amount, Transaction.TRANSFER));
O LocalDateTime não deveria ser parametrizado? Pois chamando ele aqui ele pode acabar sendo distinto na conta origem.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +		account.addStatement(new Statement(LocalDateTime.now(), amount.negate(), WITHDRAW));
Acredito que poderia chamar .now() uma única vez, e armazenar o valor e numa variável e trabalhar a partir dele, ao invés de chamar múltiplas vezes na mesma chamada de método.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +		account.addStatement(new Statement(LocalDateTime.now(), amount.negate(), WITHDRAW));
Tanto neste quanto em outros métodos.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +		}
Essas 4 linhas não está repetidas em vários métodos, que poderiam só chamar o método getAccount?

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +		return account.getStatement();
Parece um pouco confuso usar "statement" tanto para a coleção quanto para a unidade. Não deveria usar termos distintos para cada coisa?

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +		final long minutes = Duration.between(lastTransaction, LocalDateTime.now()).getSeconds() / 60;
Não seria melhor chamar Duration#getMinutes?

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +			BigDecimal incomeAmount = currentAmount.multiply(BigDecimal.valueOf(0.22));
Esse 0.22 está parecendo um magic number. Acredito que poderia estar numa constante com um nome expressivo.

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/TransferService.java
> +			String sourceCpf = accountServiceMap.get(transfer.getSourceType()).getAccount(transfer.getSourceId()).getOwner().getCpf();
Este trecho de código está repetido: ` accountServiceMap.get(transfer.getSourceType()).getAccount(transfer.getSourceId())`.
```suggestion
			String sourceCpf = sourceAccount.getOwner().getCpf();
```

2020-12-08 22:50 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +		account.setLastTransaction(savingResult.getLastTransaction());
Não poderia reusar o método getBalance?

2020-12-12 22:00 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/dto/TransferRequest.java
> +@Component
removido

2020-12-12 22:02 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +		return account.getStatement();
renomenado

2020-12-12 22:06 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +		final long minutes = Duration.between(lastTransaction, LocalDateTime.now()).getSeconds() / 60;
Até então só conhecia o método getSeconds. Dei uma olhada e econtrei o toMinutes() que converte o duration em um long com os minutos

2020-12-12 22:07 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +			BigDecimal incomeAmount = currentAmount.multiply(BigDecimal.valueOf(0.22));
feito

2020-12-12 22:09 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/TransferService.java
> +			String sourceCpf = accountServiceMap.get(transfer.getSourceType()).getAccount(transfer.getSourceId()).getOwner().getCpf();
feito

2020-12-12 22:13 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +		account.setLastTransaction(savingResult.getLastTransaction());
feito

2020-12-13 18:40 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/mapper/AccountMapper.java
> +	public AccountResponse toResponse(Account entity) {
feito

2020-12-13 18:40 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/mapper/AccountMapper.java
> +	public Account toEntity(AccountRequest request) {
extraido para uma factory

2020-12-13 18:40 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/mapper/AccountMapper.java
> +		ownerResponse.setCpf(entity.getOwner().getCpf());
feito

2020-12-13 18:40 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/controller/CreditAccountController.java
> +public class CreditAccountController {
feito

2020-12-13 18:53 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +	public Account getAccount(final UUID accountId) {
feito

2020-12-13 19:32 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +		account.addStatement(new Statement(LocalDateTime.now(), amount.negate(), WITHDRAW));
feito

2020-12-13 19:32 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +		account.addStatement(new Statement(LocalDateTime.now(), amount, Transaction.TRANSFER));
feito

2020-12-13 19:32 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/SaveAccountService.java
> +		}
feito

2020-12-13 19:32 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +	public BigDecimal getBalance(final UUID accountId) {
Ao meu ver usando Optional eu poderia estar escondendo um problema aqui. Nesse cenário o erro seria de que a conta não foi encontrada, não que o saldo esta null ou vazio. Caso a conta for encontrada não vejo um caso onde o saldo não poderá ser resolvido, a menos que eu trabalhe com a possibilidade que meus dados possam estar inválidos.

2020-12-15 22:01 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +	public BigDecimal getBalance(final UUID accountId) {
Eu concordo com o que tu falou, mas não ficou claro pra mim qual problema está sendo escondido. Me parece que ambas as abordagens visam o mesmo fim: nas situações em que é impossível determinar o saldo (porque a conta não existe), em vez de devolver um saldo eu devolvo outra coisa. Uma opção é devolver uma exceção, e outra é devolver um vazio. Existem outra possibilidades também, como devolver um null, ou devolver um número negativo (-1) -- que teriam que ser documentadas por ser abordagens que não estariam evidentes pela própria interface/assinatura do método.
Então, parece pra mim que a escolha é mais uma decisão técnica do que de semântica da operação, pois essas abordagens parecem ter o mesmo próposito/significado. Qual seria esse problema sendo escondido?

2020-12-15 22:35 UTC, rafaritter44 requested changes

2020-12-15 22:35 UTC, rafaritter44 commented on homeworks/homework2/bank/build.gradle
> +    implementation group: 'org.hibernate', name: 'hibernate-validator', version: '6.1.6.Final'
O Spring Boot tem um starter pra Bean Validation. Não seria melhor utilizar ele já que está usando Spring Boot?

2020-12-15 22:35 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/mapper/AccountMapper.java
> +			throw new IllegalArgumentException("Cannot map entity without owner");
Precisa lançar uma exception aqui? Não poderia só settar o objeto no response como null também? Me questiono o mesmo sobre a própria entity do parâmetro vir como null. Pois pra mim o mais simples é evitar exceptions, e apesar de retornar null não ser uma boa prática em geral, nesse caso eu até vejo que faz sentido, pois se ele passou um null, então o mapeamento disso é outro null. Inclusive tem frameworks de mapeamento que trabalham dessa forma.

2020-12-21 01:26 UTC, rogtejada commented on homeworks/homework2/bank/build.gradle
> +    implementation group: 'org.hibernate', name: 'hibernate-validator', version: '6.1.6.Final'
ok

2020-12-21 01:28 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/v1/mapper/AccountMapper.java
> +			throw new IllegalArgumentException("Cannot map entity without owner");
Faz sentido, pensei mais em questão da regra de negócio n fazer sentido ter esses mapeamentos em caso de null. Mas acredito q validando isso apenas na service eu consigo encapsular a toda essa lógica de negócio lá e nao ter ela duplicada.

2021-01-25 14:52 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +	public BigDecimal getBalance(final UUID accountId) {
Entendi teu ponto, alterei para Optional aqui tbm

2021-01-25 21:16 UTC, rafaritter44 commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +				.orElseThrow(() -> new InvalidAccountException(accountId));
Nesse caso tu retornaria uma exceção se não encontrar o cara. Não deveria usar map ao invés de orElseThrow? Pois assim tu tem mais casos excepcionais ainda: 1. Se não existe a conta, retorna exceção; 2. Se existe a conta e o saldo não existe, retorna empty. O client desse método vai precisar tratar mais casos. Não parece ter eliminado muito a complexidade em relação a outra abordagem, pois antes o caso 1 era o mesmo, e o caso 2 simplesmente retornava null em vez de vazio. Se fazer dessa forma que sugeri todos os casos tu mata com o vazio, e a interface fica mais explícita.

2021-02-02 23:21 UTC, rogtejada commented on homeworks/homework2/bank/src/main/java/com/rtejada/bank/service/CreditAccountService.java
> +				.orElseThrow(() -> new InvalidAccountException(accountId));
Feito

2021-02-04 19:18 UTC, merged